name: MusicianLibrary-Spigot
main: io.musician101.musicianlibrary.java.minecraft.spigot.SpigotMusicianLibrary
version: @version@
description: Change from creative and survival
authors: [ Musician101 ]
maintainer: Musician101
api-version: '1.15'
